# Generated by Django 2.0.7 on 2018-07-09 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BobaStores',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=10)),
                ('address1', models.CharField(max_length=200)),
                ('address2', models.CharField(max_length=200)),
                ('address3', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=15)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=15)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('review_count', models.DecimalField(decimal_places=0, max_digits=6)),
            ],
            options={
                'db_table': 'bubble_tea',
            },
        ),
    ]
